In [48]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

In [49]:
df = pd.read_csv('pizza_sales.csv')

In [50]:
df

,pizza_id,order_id,pizza_name_id,quantity,order_date,order_time,unit_price,total_price,pizza_size,pizza_category,pizza_ingredients,pizza_name
0,1,1,hawaiian_m,1,1/1/2015,11:38:36,13.25,13.25,M,Classic,"Sliced Ham, Pineapple, Mozzarella Cheese",The Hawaiian Pizza
1,2,2,classic_dlx_m,1,1/1/2015,11:57:40,16.00,16.00,M,Classic,"Pepperoni, Mushrooms, Red Onions, Red Peppers,...",The Classic Deluxe Pizza
2,3,2,five_cheese_l,1,1/1/2015,11:57:40,18.50,18.50,L,Veggie,"Mozzarella Cheese, Provolone Cheese, Smoked Go...",The Five Cheese Pizza
3,4,2,ital_supr_l,1,1/1/2015,11:57:40,20.75,20.75,L,Supreme,"Calabrese Salami, Capocollo, Tomatoes, Red Oni...",The Italian Supreme Pizza
4,5,2,mexicana_m,1,1/1/2015,11:57:40,16.00,16.00,M,Veggie,"Tomatoes, Red Peppers, Jalapeno Peppers, Red O...",The Mexicana Pizza
...,...,...,...,...,...,...,...,...,...,...,...,...
48615,48616,21348,ckn_alfredo_m,1,31/12/2015,21:23:10,16.75,16.75,M,Chicken,"Chicken, Red Onions, Red Peppers, Mushrooms, A...",The Chicken Alfredo Pizza
48616,48617,21348,four_cheese_l,1,31/12/2015,21:23:10,17.95,17.95,L,Veggie,"Ricotta Cheese, Gorgonzola Piccante Cheese, Mo...",The Four Cheese Pizza
48617,48618,21348,napolitana_s,1,31/12/2015,21:23:10,12.00,12.00,S,Classic,"Tomatoes, Anchovies, Green Olives, Red Onions,...",The Napolitana Pizza
48618,48619,21349,mexicana_l,1,31/12/2015,22:09:54,20.25,20.25,L,Veggie,"Tomatoes, Red Peppers, Jalapeno Peppers, Red O...",The Mexicana Pizza
48619,48620,21350,bbq_ckn_s,1,31/12/2015,23:02:05,12.75,12.75,S,Chicken,"Barbecued Chicken, Red Peppers, Green Peppers,...",The Barbecue Chicken Pizza

In [51]:
df.columns

Index(['pizza_id', 'order_id', 'pizza_name_id', 'quantity', 'order_date',
       'order_time', 'unit_price', 'total_price', 'pizza_size',
       'pizza_category', 'pizza_ingredients', 'pizza_name'],
      dtype='str')

In [52]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 48620 entries, 0 to 48619
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   pizza_id           48620 non-null  int64
 1   order_id           48620 non-null  int64
 2   pizza_name_id      48620 non-null  str
 3   quantity           48620 non-null  int64
 4   order_date         48620 non-null  str
 5   order_time         48620 non-null  str
 6   unit_price         48620 non-null  float64
 7   total_price        48620 non-null  float64
 8   pizza_size         48620 non-null  str
 9   pizza_category     48620 non-null  str
 10  pizza_ingredients  48620 non-null  str
 11  pizza_name         48620 non-null  str
dtypes: float64(2), int64(3), str(7)
memory usage: 4.5 MB

In [53]:
#df['order_date'] = pd.to_datetime(df['order_date'],format ="mixed")
df['order_date'] = pd.to_datetime(df['order_date'],dayfirst =True)

In [54]:
#df['order_time'] = pd.to_datetime(df['order_time'],format = '%h')
df['order_time'] = pd.to_datetime(df['order_time'], format='%H:%M:%S')

In [55]:
# we find out the day week and hour of the order
df['order_day'] = df['order_date'].dt.day_name()
df['order_hour'] = df['order_time'].dt.hour

In [56]:

weekdays = ['Sunday','Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday']
df['order_day'] = pd.Categorical(df['order_day'], categories=weekdays)
#df['order_day'] = pd.groupby

In [57]:
df['order_month'] = df['order_date'].dt.month_name()
df['order_month']

0         January
1         January
2         January
3         January
4         January
           ...
48615    December
48616    December
48617    December
48618    December
48619    December
Name: order_month, Length: 48620, dtype: str

In [58]:
months = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December']
df['order_month'] = pd.Categorical(df['order_month'], categories=months)

## KPI calculation first

In [59]:
'''Key Performance Indicators (KPIs) 
Total Revenue = Sum of total_price 
Total Pizzas Sold = Sum of quantity 
Total Orders = Count of unique order_id 
Average Order Value (AOV) = Total Revenue ÷ Total Orders 
Average Pizza per Order = Total Pizzas Sold ÷ Total Orders 
'''

'Key Performance Indicators (KPIs) \nTotal Revenue = Sum of total_price \nTotal Pizzas Sold = Sum of quantity \nTotal Orders = Count of unique order_id \nAverage Order Value (AOV) = Total Revenue ÷ Total Orders \nAverage Pizza per Order = Total Pizzas Sold ÷ Total Orders \n'

In [60]:
# total_revenue
total_revenue = round(df['total_price'].sum(),2)
total_revenue

np.float64(817860.05)

In [61]:
# total_pizza sold
total_pizza_sales = df['quantity'].sum()
total_pizza_sales

np.int64(49574)

In [62]:
# Total_orders
Total_orders = df['order_id'].nunique()
Total_orders

21350

In [63]:
#Average_order_value
Average_order_value = total_revenue/Total_orders
Average_order_value

np.float64(38.30726229508197)

In [64]:
# Average Pizza per order
Average_Pizza_per_order = total_pizza_sales/Total_orders
Average_Pizza_per_order

np.float64(2.321967213114754)

In [70]:
# print all the KPIs
print(f"Total Revenue: ${total_revenue}")
print(f"Total Pizzas Sold: {total_pizza_sales}.qty")
print(f"Total Orders: {Total_orders}")
print(f"Average Order Value (AOV): ${Average_order_value:.2f}")
print(f"Average Pizza per Order: {Average_Pizza_per_order:.2f}")

Total Revenue: $817860.05
Total Pizzas Sold: 49574.qty
Total Orders: 21350
Average Order Value (AOV): $38.31
Average Pizza per Order: 2.32

In [65]:
#Analysis and visualization of sales trends over time, 
# such as monthly or seasonal patterns, 
# to identify peak sales periods and 
# optimize inventory management.

In [66]:
df

,pizza_id,order_id,pizza_name_id,quantity,order_date,order_time,unit_price,total_price,pizza_size,pizza_category,pizza_ingredients,pizza_name,order_day,order_hour,order_month
0,1,1,hawaiian_m,1,2015-01-01,1900-01-01 11:38:36,13.25,13.25,M,Classic,"Sliced Ham, Pineapple, Mozzarella Cheese",The Hawaiian Pizza,Thursday,11,January
1,2,2,classic_dlx_m,1,2015-01-01,1900-01-01 11:57:40,16.00,16.00,M,Classic,"Pepperoni, Mushrooms, Red Onions, Red Peppers,...",The Classic Deluxe Pizza,Thursday,11,January
2,3,2,five_cheese_l,1,2015-01-01,1900-01-01 11:57:40,18.50,18.50,L,Veggie,"Mozzarella Cheese, Provolone Cheese, Smoked Go...",The Five Cheese Pizza,Thursday,11,January
3,4,2,ital_supr_l,1,2015-01-01,1900-01-01 11:57:40,20.75,20.75,L,Supreme,"Calabrese Salami, Capocollo, Tomatoes, Red Oni...",The Italian Supreme Pizza,Thursday,11,January
4,5,2,mexicana_m,1,2015-01-01,1900-01-01 11:57:40,16.00,16.00,M,Veggie,"Tomatoes, Red Peppers, Jalapeno Peppers, Red O...",The Mexicana Pizza,Thursday,11,January
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48615,48616,21348,ckn_alfredo_m,1,2015-12-31,1900-01-01 21:23:10,16.75,16.75,M,Chicken,"Chicken, Red Onions, Red Peppers, Mushrooms, A...",The Chicken Alfredo Pizza,Thursday,21,December
48616,48617,21348,four_cheese_l,1,2015-12-31,1900-01-01 21:23:10,17.95,17.95,L,Veggie,"Ricotta Cheese, Gorgonzola Piccante Cheese, Mo...",The Four Cheese Pizza,Thursday,21,December
48617,48618,21348,napolitana_s,1,2015-12-31,1900-01-01 21:23:10,12.00,12.00,S,Classic,"Tomatoes, Anchovies, Green Olives, Red Onions,...",The Napolitana Pizza,Thursday,21,December
48618,48619,21349,mexicana_l,1,2015-12-31,1900-01-01 22:09:54,20.25,20.25,L,Veggie,"Tomatoes, Red Peppers, Jalapeno Peppers, Red O...",The Mexicana Pizza,Thursday,22,December
48619,48620,21350,bbq_ckn_s,1,2015-12-31,1900-01-01 23:02:05,12.75,12.75,S,Chicken,"Barbecued Chicken, Red Peppers, Green Peppers,...",The Barbecue Chicken Pizza,Thursday,23,December

In [74]:
# df['pizza_ingredients'] = df['pizza_ingredients'].str.split(' ',n = 2, expand = True)
# df['pizza_ingredients'] = df['pizza_ingredients'].str.split(',')

In [ ]:
# type_of_ingridents = df['pizza_ingredients'].mode()[0]
# [type_of_ingridents]

['Pepperoni, Mushrooms, Red Onions, Red Peppers, Bacon']

In [77]:
# I want to remove duplicates valuesd
# Remove duplicates based on pizza_id
df = df.drop_duplicates(subset='pizza_id')
df['pizza_id'].unique

<bound method Series.unique of 0            1
1            2
2            3
3            4
4            5
         ...
48615    48616
48616    48617
48617    48618
48618    48619
48619    48620
Name: pizza_id, Length: 48620, dtype: int64>

In [80]:
# order 
day_sales = df.groupby('order_day',observed = False)['total_price'].sum().reset_index()
day_sales

   order_day  total_price
0     Sunday     99203.50
1     Monday    107329.55
2    Tuesday    114133.80
3  Wednesday    114408.40
4   Thursday    123528.50
5     Friday    136073.90
6   Saturday    123182.40

In [81]:
hour_sales = df.groupby('order_hour',observed = False)['total_price'].sum().reset_index()
hour_sales

    order_hour  total_price
0            9        83.00
1           10       303.65
2           11     44935.80
3           12    111877.90
4           13    106065.70
5           14     59201.40
6           15     52992.30
7           16     70055.40
8           17     86237.45
9           18     89296.85
10          19     72628.90
11          20     58215.40
12          21     42029.80
13          22     22815.15
14          23      1121.35

In [ ]:
# monthly revenue and order
# monthly_report = df.groupby('order_month').agg()

In [86]:
# % sales by categories 
sales_cat_pct = df.groupby('pizza_category')['total_price'].sum().reset_index()
sales_cat_pct['price_pct']= (sales_cat_pct['total_price']/total_revenue)*100
sales_cat_pct

  pizza_category  total_price  price_pct
0        Chicken    195919.50  23.955138
1        Classic    220053.10  26.905960
2        Supreme    208197.00  25.456311
3         Veggie    193690.45  23.682591

In [ ]:
#% sales  by pizza size and category
size_cat_pct = df.groupby(['pizza_size','pizza_category'])['total_price'].sum().reset_index()
sales_cat_pct['price_pct']= (size_cat_pct['total_price']/total_revenue)*100
size_cat_pct
 # remain something here

   pizza_size pizza_category  total_price
0           L        Chicken    102339.00
1           L        Classic     74518.50
2           L        Supreme     94258.50
3           L         Veggie    104202.70
4           M        Chicken     65224.50
5           M        Classic     60581.75
6           M        Supreme     66475.00
7           M         Veggie     57101.00
8           S        Chicken     28356.00
9           S        Classic     69870.25
10          S        Supreme     47463.50
11          S         Veggie     32386.75
12         XL        Classic     14076.00
13        XXL        Classic      1006.60

In [88]:
# total_pizza  sold by pizza _category
pizza_sold_cat = df.groupby('pizza_category')['quantity'].sum().reset_index()
pizza_sold_cat

  pizza_category  quantity
0        Chicken     11050
1        Classic     14888
2        Supreme     11987
3         Veggie     11649

Index(['pizza_id', 'order_id', 'pizza_name_id', 'quantity', 'order_date',
       'order_time', 'unit_price', 'total_price', 'pizza_size',
       'pizza_category', 'pizza_ingredients', 'pizza_name', 'order_day',
       'order_hour', 'order_month'],
      dtype='str')

In [ ]:
# there is  top_best pizza best selling
# best way of use aggrigation and groupby valuse about this 
# bhind other logic about 
top_best= pd.groupby('pizza_name').agg(total_sales ='sum')